# Site settings
title: Goka
email: your-email@domain.com
description: >
  Stream Processing Applications that simply work.
lang: en-US

baseurl: "/goka" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
git_address: https://github.com/lovoo/goka
git_edit_address: https://github.com/lovoo/goka/blob/_docs_

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: spacelab # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _tutorial
    type: docs
  values:
    layout: page
    sectionid: tutorial

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  # posts:
    # permalink: /blog/:year/:month/:day/:title/
    # output: true
